# Generated by Django 3.2 on 2022-12-20 20:43

from django.db import migrations
import products.servises
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=sorl.thumbnail.fields.ImageField(upload_to=products.servises.upload_category_path),
        ),
    ]
