# Generated by Django 3.2 on 2022-12-22 21:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0004_alter_productcomment_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productstar',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productStar_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
