# Generated by Django 3.2 on 2022-12-22 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_productstar_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productstar',
            name='percent',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
