# Generated by Django 3.2 on 2022-12-20 19:23

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=13)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('delivery_time', models.FloatField(validators=[django.core.validators.MinValueValidator(1.0)])),
                ('status', models.CharField(choices=[('warehouse', 'WAREHOUSE'), ('packaging', 'PACKAGING'), ('delivering', 'DELIVERING'), ('delivered', 'DELIVERED'), ('closed', 'CLOSED')], default='warehouse', max_length=10)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_user', to=settings.AUTH_USER_MODEL)),
                ('author_data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.userdataondelete')),
            ],
        ),
    ]
